CREATE TABLE categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name_de VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE business_cards
    ADD COLUMN category_id INT UNSIGNED NULL AFTER company,
    ADD CONSTRAINT fk_business_cards_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;

CREATE INDEX idx_business_cards_category ON business_cards (category_id);

INSERT INTO categories (name_de, name_en, sort_order, created_at) VALUES
    ('Friseur', 'Hair Salon', 10, NOW()),
    ('Kosmetikstudio', 'Beauty Salon', 20, NOW()),
    ('Nagelstudio', 'Nail Salon', 30, NOW()),
    ('Massage & Wellness', 'Massage & Wellness', 40, NOW()),
    ('Fitnessstudio', 'Gym & Fitness', 50, NOW()),
    ('Physiotherapie', 'Physiotherapy', 60, NOW()),
    ('Heilpraktiker', 'Alternative Medicine', 70, NOW()),
    ('Arztpraxis', 'Medical Practice', 80, NOW()),
    ('Zahnarztpraxis', 'Dental Practice', 90, NOW()),
    ('Psychotherapie & Coaching', 'Psychotherapy & Coaching', 100, NOW()),
    ('Tierarzt', 'Veterinarian', 110, NOW()),
    ('Apotheke', 'Pharmacy', 120, NOW()),
    ('Restaurant', 'Restaurant', 130, NOW()),
    ('Café', 'Café', 140, NOW()),
    ('Bar & Cocktailbar', 'Bar & Cocktail Bar', 150, NOW()),
    ('Bäckerei & Konditorei', 'Bakery & Pastry Shop', 160, NOW()),
    ('Imbiss & Streetfood', 'Snack Bar & Street Food', 170, NOW()),
    ('Catering', 'Catering', 180, NOW()),
    ('Eventgastronomie', 'Event Catering', 190, NOW()),
    ('Elektriker', 'Electrician', 200, NOW()),
    ('Sanitär & Heizung', 'Plumbing & Heating', 210, NOW()),
    ('Maler & Lackierer', 'Painter', 220, NOW()),
    ('Tischlerei & Schreinerei', 'Carpentry', 230, NOW()),
    ('Dachdecker', 'Roofer', 240, NOW()),
    ('Maurer & Bau', 'Construction', 250, NOW()),
    ('Fliesenleger', 'Tiler', 260, NOW()),
    ('Schlosser & Metallbau', 'Locksmith & Metalwork', 270, NOW()),
    ('Gärtner & Landschaftsbau', 'Gardening & Landscaping', 280, NOW()),
    ('KFZ-Werkstatt', 'Auto Repair Shop', 290, NOW()),
    ('Reinigungsservice', 'Cleaning Service', 300, NOW()),
    ('Umzugsservice', 'Moving Service', 310, NOW()),
    ('Handwerk (Sonstiges)', 'Trades (Other)', 320, NOW()),
    ('Rechtsanwaltskanzlei', 'Law Firm', 330, NOW()),
    ('Steuerberatung', 'Tax Advisory', 340, NOW()),
    ('Unternehmensberatung', 'Business Consulting', 350, NOW()),
    ('Versicherungsmakler', 'Insurance Broker', 360, NOW()),
    ('Immobilienmakler', 'Real Estate Agent', 370, NOW()),
    ('Finanz- & Anlageberatung', 'Financial Advisory', 380, NOW()),
    ('Personalvermittlung', 'Recruitment', 390, NOW()),
    ('Notariat', 'Notary', 400, NOW()),
    ('Fotografie', 'Photography', 410, NOW()),
    ('Grafikdesign', 'Graphic Design', 420, NOW()),
    ('Webdesign & Webentwicklung', 'Web Design & Development', 430, NOW()),
    ('Marketing- & Werbeagentur', 'Marketing & Advertising Agency', 440, NOW()),
    ('Social-Media-Beratung', 'Social Media Consulting', 450, NOW()),
    ('Video- & Filmproduktion', 'Video & Film Production', 460, NOW()),
    ('Musiker & DJ', 'Musician & DJ', 470, NOW()),
    ('Texter & Redaktion', 'Copywriting & Editorial', 480, NOW()),
    ('Illustration & Kunst', 'Illustration & Art', 490, NOW()),
    ('IT-Dienstleistung', 'IT Services', 500, NOW()),
    ('Softwareentwicklung', 'Software Development', 510, NOW()),
    ('App-Entwicklung', 'App Development', 520, NOW()),
    ('IT-Support & Systemhaus', 'IT Support', 530, NOW()),
    ('Mode & Boutique', 'Fashion & Boutique', 540, NOW()),
    ('Schmuck & Uhren', 'Jewelry & Watches', 550, NOW()),
    ('Optiker', 'Optician', 560, NOW()),
    ('Blumenladen', 'Florist', 570, NOW()),
    ('Buchhandlung', 'Bookstore', 580, NOW()),
    ('Möbel & Einrichtung', 'Furniture & Home', 590, NOW()),
    ('Elektronik & Technik', 'Electronics', 600, NOW()),
    ('Sportgeschäft', 'Sports Store', 610, NOW()),
    ('Spielwaren', 'Toy Store', 620, NOW()),
    ('Second Hand & Antiquitäten', 'Second Hand & Antiques', 630, NOW()),
    ('Nachhilfe & Tutoring', 'Tutoring', 640, NOW()),
    ('Sprachschule', 'Language School', 650, NOW()),
    ('Musikschule', 'Music School', 660, NOW()),
    ('Fahrschule', 'Driving School', 670, NOW()),
    ('Kinderbetreuung', 'Childcare', 680, NOW()),
    ('Weiterbildung & Seminare', 'Training & Seminars', 690, NOW()),
    ('Hochzeitsplanung', 'Wedding Planning', 700, NOW()),
    ('Eventplanung', 'Event Planning', 710, NOW()),
    ('Reisebüro', 'Travel Agency', 720, NOW()),
    ('Transport & Logistik', 'Transport & Logistics', 730, NOW()),
    ('Taxi & Fahrdienst', 'Taxi & Ride Service', 740, NOW()),
    ('Verein & Non-Profit', 'Association & Non-Profit', 750, NOW()),
    ('Kirche & Religionsgemeinschaft', 'Church & Religious Community', 760, NOW()),
    ('Beratungsstelle', 'Counseling Center', 770, NOW()),
    ('Landwirtschaft', 'Agriculture', 780, NOW()),
    ('Handel & Großhandel', 'Trade & Wholesale', 790, NOW()),
    ('Sonstige Dienstleistung', 'Other Services', 800, NOW()),
    ('Sonstiges', 'Other', 810, NOW());
